# Generated by Django 6.0.5 on 2026-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('especie', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], default='C', max_length=1)),
                ('nome_animal', models.CharField(blank=True, max_length=100, null=True)),
                ('raca', models.CharField(blank=True, choices=[('SRD', 'SRD'), ('Labrador', 'Labrador')], max_length=100, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('triagem', models.CharField(blank=True, choices=[('verde', 'Verde'), ('amarelo', 'Amarelo'), ('laranja', 'Laranja'), ('vermelho', 'Vermelho')], max_length=10, null=True)),
            ],
        ),
    ]
