# Generated by Django 6.0.5 on 2026-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
