# Generated by Django 6.0.5 on 2026-05-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextRag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_args', models.JSONField(blank=True, null=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pergunta')),
            ],
        ),
    ]
